"""empty message

Revision ID: 180930690663
Revises: 3e518d5fa01e
Create Date: 2015-06-14 13:20:39.321039

"""

# revision identifiers, used by Alembic.
revision = '180930690663'
down_revision = '3e518d5fa01e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lua',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('answers_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.drop_index('ix_answers_likes', table_name='answers')
    op.drop_column(u'answers', 'likes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'answers', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_answers_likes', 'answers', ['likes'], unique=False)
    op.drop_table('lua')
    ### end Alembic commands ###
