"""empty message

Revision ID: 3584fcd227ff
Revises: 180930690663
Create Date: 2015-06-14 13:36:46.842183

"""

# revision identifiers, used by Alembic.
revision = '3584fcd227ff'
down_revision = '180930690663'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
