"""empty message

Revision ID: 3e518d5fa01e
Revises: 5104f7b18a05
Create Date: 2015-06-14 12:19:15.636791

"""

# revision identifiers, used by Alembic.
revision = '3e518d5fa01e'
down_revision = '5104f7b18a05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'users', ['userid'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'userid')
    ### end Alembic commands ###
