"""empty message

Revision ID: 5643b98a405f
Revises: 3584fcd227ff
Create Date: 2015-06-14 15:18:01.049750

"""

# revision identifiers, used by Alembic.
revision = '5643b98a405f'
down_revision = '3584fcd227ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
